// app/layout.jsx
import { createTheme, MantineProvider } from '@mantine/core';
import '@mantine/core/styles.css';
import './globals.css';
import { AuthProvider } from "@/context/AuthContext";
import { Inter } from "next/font/google";
import Navbar from '@/components/Navbar'; // Make sure this path is correct

const theme = createTheme({
  colorScheme: "dark"
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Spotlink",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <MantineProvider theme={theme} defaultColorScheme='dark'>
            {/* The Navbar is now part of the layout */}
            <Navbar />
            {children}
          </MantineProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
